name: Scf Actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: ["16.x"]
        pnpm-version: ["6.0.2"]
        go-version: ["1.18.2"]
        upx-version: ["v3.96"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false
      - name: Use Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Use Buf
        uses: bufbuild/buf-setup-action@v1.4.0
      - name: Use Buf Lint
        uses: bufbuild/buf-lint-action@v1

      - name: Setup tools cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            /opt/hostedtoolcache/ghaction-upx
          key: ${{ runner.os }}-tools-store-${{ hashFiles('**/serverless.yaml') }}
          restore-keys: |
            ${{ runner.os }}-tools-store-

      - name: Stepup go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: pnpm install --global serverless serverless-tencent

      # set the scf stage by ref name
      - name: Setup stage release
        if: startsWith(github.ref_name, 'main')
        run: |
          echo "STAGE=release" >> $GITHUB_ENV

      - name: Setup stage development
        if: startsWith(github.ref_name, 'main') == false
        run: |
          echo "STAGE=test" >> $GITHUB_ENV

      - name: Prepare plugins
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          make plugins
          make buf

      # build and deploy
      - name: Make build
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          make scf-build

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: ${{ matrix.upx-version }}
          files: |
            ./main
          args: -fq

      # add configs
      - name: Add Configs
        shell: bash
        run: |
          echo "$XADMIN_CONFIG" > ./config/config_local.yml
          echo "$XADMIN_JWT_KEY" > ./config/token_jwt_key.pem
        env:
          XADMIN_CONFIG: ${{ secrets.XADMIN_CONFIG }}
          XADMIN_JWT_KEY: ${{ secrets.XADMIN_JWT_KEY }}

      - name: Deploy
        run: make scf-deploy
        env:
          TENCENT_APP_ID: ${{ secrets.TENCENT_APP_ID }}
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          SCF_NAMESPACE: ${{ secrets.SCF_NAMESPACE }}
          SERVERLESS_PLATFORM_VENDOR: ${{ secrets.SERVERLESS_PLATFORM_VENDOR }}
